version: "3.9"
services:
  drawer:
    image: ull0sm/drawer
    volumes:
      - ~/Desktop/output/data/groups:/app/data/groups
      - ~/Desktop/output/data/score_sheets:/app/data/score_sheets
    command: python automation/auto_run.py